# Generated by Django 3.1.5 on 2021-03-14 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='query',
            name='question',
            field=models.IntegerField(max_length=30),
        ),
    ]
