# Generated by Django 3.1.5 on 2021-03-14 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0002_auto_20210314_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='query',
            name='question',
        ),
        migrations.AlterField(
            model_name='query',
            name='phone',
            field=models.IntegerField(),
        ),
    ]
