# Generated by Django 3.1.5 on 2021-03-14 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myshop', '0003_auto_20210314_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='query',
            name='address',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
